---
- name: Установка и настройка PostgreSQL
  hosts: ec2_servers
  become: yes
  tasks:
    - name: Установка СУБД PostgreSQL и дополнительных пакетов
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-contrib

    - name: Убедиться, что PostgreSQL запущен и включен
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Создать базу данных
      shell: >
        sudo -u postgres psql -c "CREATE DATABASE oscar_db;"

    - name: Создать пользователя
      shell: >
        sudo -u postgres psql -c "CREATE USER oscar WITH PASSWORD 'your_password';"

    - name: Дать пользователю oscar все привилегии на базе данных oscar_db
      shell: >
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE oscar_db TO oscar;"

